### ISSUE TITLE
RuntimeError: Failed precondition: From /job:tpu_worker/replica:0/task:0:

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2650]
Hi
I am getting this error with pytoch XLA, could you asisst me how I can resolve RuntimeError: Failed precondition: From /job:tpu_worker/replica:0/task:0: ? thanks 

> 2020-11-25 03:08:31.472347: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   ROOT %tuple.10094 = (f32[]) tuple(f32[] %add.10093)
el/0 I1124 19:40:57.807390 882917 main shadow.py:122 > 2020-11-25 03:08:31.472354: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] }
el/0 I1124 19:40:57.807426 882917 main shadow.py:122 > 2020-11-25 03:08:31.472361: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
el/0 I1124 19:40:57.807461 882917 main shadow.py:122 > 2020-11-25 03:08:31.472368: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
el/0 I1124 19:40:57.807498 882917 main shadow.py:122 > 2020-11-25 03:08:31.472375: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] OutputShape: (f32[])
el/0 I1124 19:40:57.807533 882917 main shadow.py:122 > 2020-11-25 03:08:31.472383: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
el/0 I1124 19:40:57.807568 882917 main shadow.py:122 > 2020-11-25 03:08:31.472393: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] StackTrace:
el/0 I1124 19:40:57.807603 882917 main shadow.py:122 > 2020-11-25 03:08:31.472400: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] *** Begin stack trace ***
el/0 I1124 19:40:57.807638 882917 main shadow.py:122 > 2020-11-25 03:08:31.472407: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	tensorflow::CurrentStackTrace()
el/0 I1124 19:40:57.807673 882917 main shadow.py:122 > 2020-11-25 03:08:31.472414: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	xla::util::ReportComputationError(tensorflow::Status const&, absl::lts_2020_02_25::Span<xla::XlaComputation const* const>, absl::lts_2020_02_25::Span<xla::Shape const* const>)
el/0 I1124 19:40:57.807708 882917 main shadow.py:122 > 2020-11-25 03:08:31.472424: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	xla::XrtComputationClient::CheckCompileStatus(tensorflow::Status const&, std::vector<xla::ComputationClient::CompileInstance, std::allocator<xla::ComputationClient::CompileInstance> > const&, xla::XrtComputationClient::SessionWork const&)
el/0 I1124 19:40:57.807743 882917 main shadow.py:122 > 2020-11-25 03:08:31.472431: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	
el/0 I1124 19:40:57.807778 882917 main shadow.py:122 > 2020-11-25 03:08:31.472438: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	xla::util::MultiWait::Complete(std::function<void ()> const&)
el/0 I1124 19:40:57.807813 882917 main shadow.py:122 > 2020-11-25 03:08:31.472446: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	
el/0 I1124 19:40:57.807848 882917 main shadow.py:122 > 2020-11-25 03:08:31.472454: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	
el/0 I1124 19:40:57.807901 882917 main shadow.py:122 > 2020-11-25 03:08:31.472461: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	
el/0 I1124 19:40:57.807958 882917 main shadow.py:122 > 2020-11-25 03:08:31.472469: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	clone
el/0 I1124 19:40:57.808011 882917 main shadow.py:122 > 2020-11-25 03:08:31.472475: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] *** End stack trace ***
el/0 I1124 19:40:57.808046 882917 main shadow.py:122 > 2020-11-25 03:08:31.472482: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
el/0 I1124 19:40:57.808086 882917 main shadow.py:122 > 2020-11-25 03:08:31.472489: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] Status: Failed precondition: From /job:tpu_worker/replica:0/task:0:
el/0 I1124 19:40:57.808122 882917 main shadow.py:122 > 2020-11-25 03:08:31.472496: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 2 root error(s) found.
el/0 I1124 19:40:57.808160 882917 main shadow.py:122 > 2020-11-25 03:08:31.472503: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   (0) Failed precondition: Expected comparison type SIGNED.
el/0 I1124 19:40:57.808195 882917 main shadow.py:122 > 2020-11-25 03:08:31.472510: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] actual: UNSIGNED
el/0 I1124 19:40:57.808230 882917 main shadow.py:122 > 2020-11-25 03:08:31.472517: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] operand: s64[64,128,1]
el/0 I1124 19:40:57.808265 882917 main shadow.py:122 > 2020-11-25 03:08:31.472524: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
el/0 I1124 19:40:57.808300 882917 main shadow.py:122 > 2020-11-25 03:08:31.472531: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	 [[{{node XRTCompile}}]]
el/0 I1124 19:40:57.808335 882917 main shadow.py:122 > 2020-11-25 03:08:31.472540: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	 [[XRTCompile_G6]]
el/0 I1124 19:40:57.808370 882917 main shadow.py:122 > 2020-11-25 03:08:31.472547: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   (1) Failed precondition: Expected comparison type SIGNED.
el/0 I1124 19:40:57.808405 882917 main shadow.py:122 > 2020-11-25 03:08:31.472554: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] actual: UNSIGNED
el/0 I1124 19:40:57.808440 882917 main shadow.py:122 > 2020-11-25 03:08:31.472561: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] operand: s64[64,128,1]
el/0 I1124 19:40:57.808479 882917 main shadow.py:122 > 2020-11-25 03:08:31.472568: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
el/0 I1124 19:40:57.808514 882917 main shadow.py:122 > 2020-11-25 03:08:31.472575: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	 [[{{node XRTCompile}}]]
el/0 I1124 19:40:57.808549 882917 main shadow.py:122 > 2020-11-25 03:08:31.472582: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 0 successful operations.
el/0 I1124 19:40:57.808584 882917 main shadow.py:122 > 2020-11-25 03:08:31.472589: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 0 derived errors ignored.
el/0 I1124 19:40:57.808620 882917 main shadow.py:122 > Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workdir/seq2seq/finetune_t5_trainer.py", line 247, in <module>
    main()
  File "/workdir/seq2seq/finetune_t5_trainer.py", line 170, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/transformers/trainer.py", line 805, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/transformers/trainer.py", line 852, in _maybe_log_save_evaluate
    tr_loss_scalar = tr_loss.item()
RuntimeError: Failed precondition: From /job:tpu_worker/replica:0/task:0:
el/0 I1124 19:40:57.808656 882917 main shadow.py:122 > 2 root error(s) found.
el/0 I1124 19:40:57.808692 882917 main shadow.py:122 >   (0) Failed precondition: Expected comparison type SIGNED.
el/0 I1124 19:40:57.808727 882917 main shadow.py:122 > actual: UNSIGNED
el/0 I1124 19:40:57.808762 882917 main shadow.py:122 > operand: s64[64,128,1]
el/0 I1124 19:40:57.808797 882917 main shadow.py:122 > 
el/0 I1124 19:40:57.808832 882917 main shadow.py:122 > 	 [[{{node XRTCompile}}]]
el/0 I1124 19:40:57.808867 882917 main shadow.py:122 > 	 [[XRTCompile_G6]]
el/0 I1124 19:40:57.808902 882917 main shadow.py:122 >   (1) Failed precondition: Expected comparison type SIGNED.
el/0 I1124 19:40:57.808950 882917 main shadow.py:122 > actual: UNSIGNED
el/0 I1124 19:40:57.809009 882917 main shadow.py:122 > operand: s64[64,128,1]
el/0 I1124 19:40:57.809045 882917 main shadow.py:122 > 
el/0 I1124 19:40:57.809080 882917 main shadow.py:122 > 	 [[{{node XRTCompile}}]]

**Comment by JackCaoG** [comment]
hmm, the real error is 
```
el/0 I1124 19:40:57.808160 882917 main shadow.py:122 > 2020-11-25 03:08:31.472503: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] (0) Failed precondition: Expected comparison type SIGNED.
el/0 I1124 19:40:57.808195 882917 main shadow.py:122 > 2020-11-25 03:08:31.472510: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] actual: UNSIGNED
el/0 I1124 19:40:57.808230 882917 main shadow.py:122 > 2020-11-25 03:08:31.472517: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] operand: s64[64,128,1]
el/0 I1124 19:40:57.808265 882917 main shadow.py:122 > 2020-11-25 03:08:31.472524: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]
el/0 I1124 19:40:57.808300 882917 main shadow.py:122 > 2020-11-25 03:08:31.472531: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] [[{{node XRTCompile}}]]
el/0 I1124 19:40:57.808335 882917 main shadow.py:122 > 2020-11-25 03:08:31.472540: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] [[XRTCompile_G6]]
```

Did you update to use latest nightly? I thought I fixed this by https://github.com/pytorch/xla/pull/2646. Could you share a small repo?

**Comment by zcain117** [comment]
I think the Pytorch Lightning team is seeing this too. @borda were you using latest nightly when you saw it?

**Comment by Borda** [comment]
we have these problems with 1.6, in particular using this docker image XLA 1.6 for py3.6 and 3.7
https://hub.docker.com/r/pytorchlightning/pytorch_lightning/tags?page=1&ordering=last_updated&name=xla

**Comment by rabeehk** [comment]
Hi
This is how I am using pytroch xla, I make a machine with pytroch xla image and then I activate the conda to use it, do you think conda environment are updated? for me this freezes when I test it on nightly version? I will share you the repo internally. thanks

**Comment by rabeehk** [comment]
I tested latest 1.7 version it still happens, with latest nightly version, with nightly version it freezes. This issue is blocking me, I will send @JackCaoG  the link to the repo internally. thanks

**Comment by Borda** [comment]
For us, it is a blocker as we cannot merge any PR till our tests are passing on all env/devices :/

**Comment by rabeehk** [comment]
Hi
Thank you for the reply. As said on docker version 1.7 it works fine, could
you give please which version date is matching that image, so I could
choose that date for now to be able to continue, as currently I cannot run
any of the models. That would be great to know that version as a temporary
solution.
thank you.
Best regards
Rabeeh

**Comment by Borda** [comment]
We are testing 1.7 ver if it helps... https://github.com/PyTorchLightning/pytorch-lightning/pull/4891

**Comment by zcain117** [comment]
@Borda this is very useful. This makes it sound like a TPU issue since you are using the same VM software the whole time but suddenly the test is failing. I see here you are using `pytorch-nightly` as the TPU version at this spot: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/dockers/tpu-tests/tpu_test_cases.jsonnet#L17

Could you try using `pytorch-1.6` and `pytorch-1.7` to match the VM software?


@rabeehk just to clarify: you said "docker files are more updated" compared to the conda envs. What did you mean by this? And what about your TPU? Are you creating it through Google Cloud Compute Engine? And if so, what kind of TPU software are you using? If you use the `1.7` docker image, you should make sure your TPU version is `pytorch-1.7`

**Comment by JackCaoG** [comment]
That check and failure is from a recent commit. Like @zcain117 suggested, if you are using pt/xla_1.6 or pt?xla_1.7, could you check if your TPU runtime version matched with the pt/xla version?

**Comment by Borda** [comment]
> if you are using pt/xla_1.6 or pt?xla_1.7, could you check if your TPU runtime version matched with the pt/xla version?

yes, aligning TPU/XLA versions solves all our issue, for the record, we do not run nightly atm

**Comment by edgarriba** [comment]
In our case `pytorch-1.6` and `pytorch-1.7` makes ~50% of our tests to crash https://github.com/kornia/kornia/pull/807
https://app.circleci.com/pipelines/github/kornia/kornia/2271/workflows/6e519dbc-607e-4ac7-a76c-9e209b18c4fe/jobs/5213

Besides, as a general comment we have been noticing that the obtained precision compared to cpu or gpu is way more low when the test is done with xla devices. We ended up having to decrease the error tolerance for a lot of the tests.

**Comment by zcain117** [comment]
@edgarriba it looks like your tests are using `pytorch-nightly` for the TPU software version, both on master: https://github.com/kornia/kornia/blob/master/docker/tpu-tests/tpu_test_cases.jsonnet#L17

as well as the commit that kicked off that CircleCI run: https://github.com/kornia/kornia/blob/9560fad6abec5921e4f5ca644f627acf6382ed9f/docker/tpu-tests/tpu_test_cases.jsonnet#L17

If you're using `gcr.io/tpu-pytorch/xla:r1.7` as the docker image for the VM, you'd need to use `pytorch-1.7` as the TPU software. And `gcr.io/tpu-pytorch/xla:r1.6` would need `pytorch-1.6` as the TPU softtware.

We are expecting soon (in the next few months) we won't have this separate software thing and this process will be streamlined, but for now the TPU software and the VM software need to match or you'll get bugs

**Comment by rabeehkarimimahabadi** [comment]
I am still getting this and this is blocking me, any solution for this ? thanks 

operand: f32[64,104,512]

	 [[{{node XRTCompile}}]]
  (1) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,104,512]

	 [[{{node XRTCompile}}]]
	 [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Exception in device=TPU:6: Failed precondition: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,113,512]

	 [[{{node XRTCompile}}]]
  (1) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,113,512]

	 [[{{node XRTCompile}}]]
	 [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/home/rabeeh/ruse/seq2seq/finetune_t5_trainer.py", line 242, in _mp_fn
    main()
  File "/home/rabeeh/ruse/seq2seq/finetune_t5_trainer.py", line 179, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/home/rabeeh/ruse/seq2seq/trainers/trainer.py", line 812, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)
  File "/home/rabeeh/ruse/seq2seq/trainers/trainer.py", line 859, in _maybe_log_save_evaluate
    tr_loss_scalar = tr_loss.item()
RuntimeError: Failed precondition: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,113,512]

	 [[{{node XRTCompile}}]]
  (1) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,113,512]

	 [[{{node XRTCompile}}]]
	 [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Exception in device=TPU:1: Failed precondition: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,85,512]

	 [[{{node XRTCompile}}]]
  (1) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,85,512]

	 [[{{node XRTCompile}}]]
	 [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/home/rabeeh/ruse/seq2seq/finetune_t5_trainer.py", line 242, in _mp_fn
    main()
  File "/home/rabeeh/ruse/seq2seq/finetune_t5_trainer.py", line 179, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/home/rabeeh/ruse/seq2seq/trainers/trainer.py", line 812, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)
  File "/home/rabeeh/ruse/seq2seq/trainers/trainer.py", line 859, in _maybe_log_save_evaluate
    tr_loss_scalar = tr_loss.item()
RuntimeError: Failed precondition: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,85,512]

	 [[{{node XRTCompile}}]]
  (1) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[64,85,512]

	 [[{{node XRTCompile}}]]
	 [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File "xla_spawn.py", line 106, in <module>
    main()
  File "xla_spawn.py", line 90, in main
    xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 395, in spawn
    start_method=start_method)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 112, in join
    (error_index, exitcode)
Exception: process 5 terminated with exit code 17

**Comment by zcain117** [comment]
@rabeehk can you try:
1. delete your TPU
2. make a new TPU and note the TPU software version
3. make a new VM and make sure the VM software matches the TPU software
