### ISSUE TITLE
Slow training on multiple TPUs from bottleneck

### ISSUE THREAD

**Issue by david-littlefield** [pytorch/xla#3080]
## 🐛 Bug

`pt-xla-profiler: TransferFromServerTime too frequent: 314 counts during 80 steps
pt-xla-profiler: Op(s) not lowered: aten::sgn_out,  Please open a GitHub issue with the above op lowering requests.`

It takes longer to train an epoch with TPUs on Colab using 8 cores than my 1080 ti 11GB GPU. I've been stumbling my way through using the TPU in PyTorch Lightning. I've also been informed that this is an issue of Operation(s) not being lowered for XLA, and that PyTorch XLA is the place to create an issue and discuss the support of those operations. However, I don't know where to go from here.

### To Reproduce

Run the [notebook](https://colab.research.google.com/drive/1t0kgqnugEeMopBmQDZ7EzvnHjBPcjC1l?usp=sharing) in Coab.

### Expected behavior

Train the model faster than my 1080 ti 11GB GPU.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		
	- processor:         x86_64
	- python:            3.7.11

**Comment by miladm** [comment]
Based on the error above, `sgn_out` need to be lowered. 

Are you using complex numbers in your model where `sgn_out` is called? Maybe in the loss function?

If so, this [issue](https://github.com/pytorch/xla/pull/3045) should improve the slow training.

**Comment by david-littlefield** [comment]
Thanks @miladm! I'll try that.

**Comment by rwightman** [comment]
@miladm @david-littlefield `sgn` is used in the derivative of `abs` (regardless of whether or not you use complex numbers) ever since abs was updated to support complex numbers, the lowering of sgn should be pretty high priority because this is easy to run into w/ abs or l1 loss

**Comment by david-littlefield** [comment]
That's good to know, thanks @rwightman! 

Hi @miladm, I'm currently taking a C++ course and will attempt your suggestions afterward.

**Comment by miladm** [comment]
@david-littlefield `sgn` implementation is available on the `master` branch. Let us know how this feature addition helps your training speed performance.

**Comment by JackCaoG** [comment]
If you are using colab, you might want to checkout https://github.com/pytorch/xla/issues/2933 regarding a known issue and workaround of running pt/xla nightly on colab.

**Comment by david-littlefield** [comment]
Thanks @miladm  and @JackCaoG! 

I'd like to be able to help lower operations for PyTorch XLA. I'm almost done with a C++ course. Then, I will complete the lowering tutorial by @tyoc213. 

In the meantime, how do I make use of the `sgn` implementation in the master branch? I run into the same bottleneck when I rerun the project in colab. 

I also run into an `undefined symbol` error when I implement the solution from checkout #2933 (using the latest pytorch version). The solutions to the `undefined symbol` error suggest to use an older version of PyTorch. 

This is my first time working on something of this caliber so please excuse my naivety on the subject 😅.

**Comment by miladm** [comment]
You're welcome @david-littlefield!

To use the `sgn` op, install PyTorch XLA `master` branch latest commit. The rest is taken care of automatically; in general, when an op is lowered in PT/XLA, your ML program automatically runs that operation on the TPU. 

Happy to answer your questions re: how to lower ops for PT/XLA. Feel free to ping us!

Re: the `undefined symbol` error, it seems your problem is already addressed in the parallel issue. Happy to answer any follow ups as needed.

**Comment by david-littlefield** [comment]
@miladm I cloned the master branch of the XLA repository and moved the "torch_xla" subdirectory into the "/usr/local/lib/python3.7/dist-packages/" subdirectory in Google Colab. I must be doing something wrong because I'm still experiencing the same bottleneck.

**Comment by JackCaoG** [comment]
@david-littlefield Please refer to [this colab](https://colab.sandbox.google.com/github/pytorch/xla/blob/master/contrib/colab/getting-started.ipynb), there is a cell explain how to switch to nightly in colab. Note you might run into some issue with libraries, please refer to [this issue](https://github.com/pytorch/xla/issues/2933) for solution.

**Comment by david-littlefield** [comment]
Thanks, @JackCaoG. I tried that but I'm still getting an error message. I've found solutions to similar issues that have suggested downgrading, upgrading certain torch related libraries, and installing from source. What would you recommend?

```
Traceback (most recent call last):
  File "/content/nuwave/trainer.py", line 1, in <module>
    from lightning_model import NuWave
  File "/content/nuwave/lightning_model.py", line 9, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py", line 27, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_AVAILABLE
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/imports.py", line 93, in <module>
    from pytorch_lightning.utilities.xla_device import XLADeviceUtils  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/xla_device.py", line 23, in <module>
    import torch_xla.core.xla_model as xm
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/__init__.py", line 101, in <module>
    import _XLAC
ImportError: /usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops4item4callERKNS_6TensorE
```

**Comment by JackCaoG** [comment]
@david-littlefield It seems like you are using pt/xla through pytorch lighting. I think you need to manually install pytorch lighting nightly since our setup script will not reinstall lighting. I have never done that before through. @kaushikb11 is there an easy way to do this for colab?

**Comment by david-littlefield** [comment]
@JackCaoG That's good to know, thanks!

**Comment by kaushikb11** [comment]
@david-littlefield Seems like the versions you installed are incompatible. Could you try this out?

```python
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.8-cp37-cp37m-linux_x86_64.whl

!pip install pytorch-lightning
```

**Comment by david-littlefield** [comment]
Thanks, @kaushikb11. I tried your suggestion and the script runs but nothing prints to the console. Also, will this version of Torch XLA include the recent `sgn` implementation that was added?

**Comment by kaushikb11** [comment]
@david-littlefield I don't think so. Could you follow the instructions the XLA folks mentioned to install XLA master & *then* install PytorchLightning?

**Comment by miladm** [comment]
`torch_xla-1.8` does not. `sgn` was recently pushed to master and will be part of an upcoming release (most likely 1.10
 - @JackCaoG can confirm). `sgn` is available via the nightly releases for the time being.

**Comment by david-littlefield** [comment]
@kaushikb11 I think I've done that but I receive the [error](https://github.com/pytorch/xla/issues/3080#issuecomment-908868051) from earlier. I just tried it again and got the same error but maybe I'm doing something incorrectly.

@miladm Do I need to build Torch XLA from source to use nightly? I don't know where to go from here.

Also, is PyTorch XLA nightly compatible with PyTorch Lightning? 

```
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.9-cp37-cp37m-linux_x86_64.whl
VERSION = "nightly"
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION
!pip install pytorch-lightning

import os 
os.environ['LD_LIBRARY_PATH']='/usr/local/lib'

!echo $LD_LIBRARY_PATH
!sudo ln -s /usr/local/lib/libmkl_intel_lp64.so /usr/local/lib/libmkl_intel_lp64.so.1
!sudo ln -s /usr/local/lib/libmkl_intel_thread.so /usr/local/lib/libmkl_intel_thread.so.1
!sudo ln -s /usr/local/lib/libmkl_core.so /usr/local/lib/libmkl_core.so.1

!ldconfig
!ldd /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so
```

**Comment by miladm** [comment]
Yes, since `sgn` is currently available in the `master` branch only, you will need to build PT/XLA from source using nightly.

**Comment by david-littlefield** [comment]
Cool, I'll give that a try. Thanks, @miladm!

**Comment by david-littlefield** [comment]
@miladm @kaushikb11  I'm still getting the same error. Any suggestions?

**Comment by david-littlefield** [comment]
@miladm @kaushikb11 @JackCaoG It doesn't seem like PyTorch Lightning is compatible with PyTorch XLA nightly. Maybe the `sgn` implementation would work with PyTorch Lightning once it's included in the official release of PyTorch XLA. But 3+ weeks waiting period for each lowered operation makes it impractical for me to invest the time needed to learn how to lower operations.
